# Generated by Django 5.0.1 on 2024-02-01 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoremanagementapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('midterm_score', models.FloatField()),
                ('final_score', models.FloatField()),
                ('new_score_1', models.FloatField(blank=True, null=True)),
                ('new_score_2', models.FloatField(blank=True, null=True)),
                ('new_score_3', models.FloatField(blank=True, null=True)),
                ('new_score_4', models.FloatField(blank=True, null=True)),
                ('new_score_5', models.FloatField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('lessons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoremanagementapp.lesson')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
