# Generated by Django 5.0.1 on 2024-02-01 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoremanagementapp', '0002_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grades', models.ManyToManyField(to='scoremanagementapp.grade')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoremanagementapp.lesson')),
            ],
        ),
    ]
