# Generated by Django 5.0.1 on 2024-02-13 09:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_forumpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
