# Generated by Django 5.0.1 on 2024-02-20 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_schoolemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolemail',
            name='user',
        ),
    ]
