# Generated by Django 5.0.1 on 2024-02-22 05:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_schoolemail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
