# Generated by Django 5.0.1 on 2024-02-25 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_lesson_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='name',
        ),
    ]
